#!/usr/bin/env python3
"""Rebuild docs/INDEX.md as a catalog table of every skill in the repo.

Usage:
    python scripts/generate_index.py            # rewrite docs/INDEX.md
    python scripts/generate_index.py --check    # exit 1 if INDEX.md is stale

The generator is idempotent: running it twice in a row produces byte
identical output on the second run.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
INDEX_PATH = REPO_ROOT / "docs" / "INDEX.md"

CATEGORY_ORDER = [
    "core",
    "planning",
    "architecture",
    "backend",
    "frontend",
    "database",
    "devops",
    "quality",
    "security",
    "delivery",
]

CATEGORY_TITLES = {
    "core": "Core",
    "planning": "Planning",
    "architecture": "Architecture",
    "backend": "Backend",
    "frontend": "Frontend",
    "database": "Database",
    "devops": "DevOps",
    "quality": "Quality",
    "security": "Security",
    "delivery": "Delivery",
}


def load_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{path} missing frontmatter")
    _, raw, _ = text.split("---", 2)
    return yaml.safe_load(raw)


def collect_skills() -> list[dict]:
    skills = []
    for skill_file in sorted(SKILLS_DIR.glob("*/*/SKILL.md")):
        fm = load_frontmatter(skill_file)
        folder_category_dir = skill_file.parent.parent.name  # e.g. 30-backend
        skills.append(
            {
                "name": fm.get("name", skill_file.parent.name),
                "category": fm.get("category", ""),
                "category_dir": folder_category_dir,
                "description": fm.get("description", ""),
                "tags": fm.get("tags", []) or [],
                "maturity": fm.get("maturity", ""),
                "path": skill_file.relative_to(REPO_ROOT).as_posix(),
            }
        )
    return skills


def render_index(skills: list[dict]) -> str:
    lines = []
    lines.append("# Skill Index")
    lines.append("")
    lines.append(
        "This file is generated by `python scripts/generate_index.py`. Do not edit by hand."
    )
    lines.append("")

    by_category: dict[str, list[dict]] = {c: [] for c in CATEGORY_ORDER}
    for skill in skills:
        by_category.setdefault(skill["category"], []).append(skill)

    total = len(skills)
    lines.append(f"Total skills: {total}")
    lines.append("")

    for category in CATEGORY_ORDER:
        category_skills = sorted(by_category.get(category, []), key=lambda s: s["name"])
        if not category_skills:
            continue
        title = CATEGORY_TITLES.get(category, category.title())
        lines.append(f"## {title}")
        lines.append("")
        lines.append("| Skill | Category | Description | Tags | Maturity |")
        lines.append("| --- | --- | --- | --- | --- |")
        for skill in category_skills:
            link = f"[{skill['name']}](../{skill['path']})"
            tags = ", ".join(skill["tags"])
            lines.append(
                f"| {link} | {skill['category']} | {skill['description']} | {tags} | {skill['maturity']} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if docs/INDEX.md is stale")
    args = parser.parse_args()

    skills = collect_skills()
    rendered = render_index(skills)

    if args.check:
        existing = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if existing != rendered:
            print("docs/INDEX.md is stale. Run 'python scripts/generate_index.py' to regenerate it.")
            return 1
        print("docs/INDEX.md is up to date.")
        return 0

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {INDEX_PATH.relative_to(REPO_ROOT)} with {len(skills)} skill(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
